Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Ioport:  (at 3)
          Input: in1, False (at 3)
        Ioport:  (at 4)
          Input: in2, False (at 4)
        Ioport:  (at 5)
          Input: CLK, False (at 5)
        Ioport:  (at 6)
          Output: out1, False (at 6)
        Ioport:  (at 7)
          Output: out2, False (at 7)
      Decl:  (at 10)
        Integer: i, True (at 10)
          Width:  (at 10)
            IntConst: 31 (at 10)
            IntConst: 0 (at 10)
      Always:  (at 11)
        SensList:  (at 11)
          Sens: posedge (at 11)
            Identifier: CLK (at 11)
        Block: None (at 11)
          BlockingSubstitution:  (at 12)
            Lvalue:  (at 12)
              Identifier: out1 (at 12)
            Rvalue:  (at 12)
              Identifier: out2 (at 12)
      Always:  (at 14)
        SensList:  (at 14)
          Sens: level (at 14)
            Identifier: in1 (at 14)
        Block: None (at 14)
          IfStatement:  (at 16)
            Identifier: in2 (at 16)
            Block: None (at 16)
              BlockingSubstitution:  (at 17)
                Lvalue:  (at 17)
                  Identifier: out1 (at 17)
                Rvalue:  (at 17)
                  Identifier: in2 (at 17)
              BlockingSubstitution:  (at 18)
                Lvalue:  (at 18)
                  Identifier: out2 (at 18)
                Rvalue:  (at 18)
                  Identifier: in2 (at 18)
            BlockingSubstitution:  (at 21)
              Lvalue:  (at 21)
                Identifier: out1 (at 21)
              Rvalue:  (at 21)
                Identifier: in2 (at 21)
          BlockingSubstitution:  (at 23)
            Lvalue:  (at 23)
              Identifier: out1 (at 23)
            Rvalue:  (at 23)
              Plus:  (at 23)
                Identifier: out2 (at 23)
                IntConst: 1 (at 23)
