Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Ioport:  (at 3)
          Input: CLK, False (at 3)
        Ioport:  (at 4)
          Input: RST, False (at 4)
        Ioport:  (at 5)
          Input: enable, False (at 5)
        Ioport:  (at 6)
          Input: value, False (at 6)
            Width:  (at 6)
              IntConst: 31 (at 6)
              IntConst: 0 (at 6)
        Ioport:  (at 7)
          Output: led, False (at 7)
            Width:  (at 7)
              IntConst: 7 (at 7)
              IntConst: 0 (at 7)
      Decl:  (at 9)
        Reg: count, False (at 9)
          Width:  (at 9)
            IntConst: 31 (at 9)
            IntConst: 0 (at 9)
      Decl:  (at 10)
        Reg: state, False (at 10)
          Width:  (at 10)
            IntConst: 7 (at 10)
            IntConst: 0 (at 10)
      Assign:  (at 11)
        Lvalue:  (at 11)
          Identifier: led (at 11)
        Rvalue:  (at 11)
          Partselect:  (at 11)
            Identifier: count (at 11)
            IntConst: 23 (at 11)
            IntConst: 16 (at 11)
      Always:  (at 12)
        SensList:  (at 12)
          Sens: posedge (at 12)
            Identifier: CLK (at 12)
        Block: None (at 13)
          IfStatement:  (at 14)
            Identifier: RST (at 14)
            NonblockingSubstitution:  (at 15)
              Lvalue:  (at 15)
                Identifier: count (at 15)
              Rvalue:  (at 15)
                Identifier: state (at 15)
            NonblockingSubstitution:  (at 17)
              Lvalue:  (at 17)
                Identifier: count (at 17)
              Rvalue:  (at 17)
                IntConst: 1 (at 17)
      Always:  (at 19)
        SensList:  (at 19)
          Sens: level (at 19)
            Identifier: CLK (at 19)
          Sens: level (at 19)
            Identifier: state (at 19)
          Sens: level (at 19)
            Identifier: value (at 19)
        Block: None (at 20)
          IfStatement:  (at 21)
            Identifier: RST (at 21)
            NonblockingSubstitution:  (at 22)
              Lvalue:  (at 22)
                Identifier: count (at 22)
              Rvalue:  (at 22)
                Identifier: value (at 22)
            NonblockingSubstitution:  (at 24)
              Lvalue:  (at 24)
                Identifier: state (at 24)
              Rvalue:  (at 24)
                Identifier: CLK (at 24)
          IfStatement:  (at 25)
            Identifier: enable (at 25)
            Block: None (at 26)
              NonblockingSubstitution:  (at 27)
                Lvalue:  (at 27)
                  Identifier: count (at 27)
                Rvalue:  (at 27)
                  Identifier: state (at 27)
              NonblockingSubstitution:  (at 28)
                Lvalue:  (at 28)
                  Identifier: state (at 28)
                Rvalue:  (at 28)
                  Identifier: CLK (at 28)
            Block: None (at 31)
              NonblockingSubstitution:  (at 32)
                Lvalue:  (at 32)
                  Identifier: count (at 32)
                Rvalue:  (at 32)
                  Identifier: value (at 32)
      Always:  (at 35)
        SensList:  (at 35)
          Sens: level (at 35)
            Identifier: CLK (at 35)
          Sens: level (at 35)
            Identifier: state (at 35)
        Block: None (at 36)
          IfStatement:  (at 37)
            Identifier: RST (at 37)
            Block: None (at 38)
              IfStatement:  (at 39)
                Identifier: enable (at 39)
                NonblockingSubstitution:  (at 40)
                  Lvalue:  (at 40)
                    Identifier: count (at 40)
                  Rvalue:  (at 40)
                    Identifier: state (at 40)
                NonblockingSubstitution:  (at 42)
                  Lvalue:  (at 42)
                    Identifier: count (at 42)
                  Rvalue:  (at 42)
                    Identifier: value (at 42)
            Block: None (at 45)
              NonblockingSubstitution:  (at 46)
                Lvalue:  (at 46)
                  Identifier: state (at 46)
                Rvalue:  (at 46)
                  IntConst: 1 (at 46)
              IfStatement:  (at 47)
                Identifier: enable (at 47)
                NonblockingSubstitution:  (at 48)
                  Lvalue:  (at 48)
                    Identifier: count (at 48)
                  Rvalue:  (at 48)
                    Identifier: RST (at 48)
                NonblockingSubstitution:  (at 50)
                  Lvalue:  (at 50)
                    Identifier: count (at 50)
                  Rvalue:  (at 50)
                    IntConst: 1 (at 50)
          IfStatement:  (at 52)
            Identifier: CLK (at 52)
            NonblockingSubstitution:  (at 53)
              Lvalue:  (at 53)
                Identifier: count (at 53)
              Rvalue:  (at 53)
                IntConst: 1 (at 53)
      Always:  (at 55)
        SensList:  (at 55)
          Sens: level (at 55)
            Identifier: enable (at 55)
          Sens: level (at 55)
            Identifier: count (at 55)
        Block: None (at 56)
          BlockingSubstitution:  (at 57)
            Lvalue:  (at 57)
              Identifier: count (at 57)
            Rvalue:  (at 57)
              Identifier: enable (at 57)
          CaseStatement:  (at 58)
            Identifier: state (at 58)
            Case:  (at 59)
              IntConst: 1 (at 59)
              NonblockingSubstitution:  (at 59)
                Lvalue:  (at 59)
                  Identifier: enable (at 59)
                Rvalue:  (at 59)
                  Identifier: count (at 59)
            Case:  (at 60)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
      Always:  (at 63)
        SensList:  (at 0)
          Sens: all (at 0)
        BlockingSubstitution:  (at 64)
          Lvalue:  (at 64)
            Identifier: count (at 64)
          Rvalue:  (at 64)
            Identifier: state (at 64)
      Always:  (at 65)
        SensList:  (at 65)
          Sens: level (at 65)
            Identifier: enable (at 65)
        Block: None (at 66)
          IfStatement:  (at 67)
            And:  (at 67)
              Identifier: a (at 67)
              Identifier: enable (at 67)
            NonblockingSubstitution:  (at 68)
              Lvalue:  (at 68)
                Identifier: count (at 68)
              Rvalue:  (at 68)
                And:  (at 68)
                  Identifier: a (at 68)
                  Identifier: b (at 68)
            NonblockingSubstitution:  (at 70)
              Lvalue:  (at 70)
                Identifier: count (at 70)
              Rvalue:  (at 70)
                Or:  (at 70)
                  Identifier: enable (at 70)
                  Identifier: d (at 70)
          NonblockingSubstitution:  (at 71)
            Lvalue:  (at 71)
              Identifier: count (at 71)
            Rvalue:  (at 71)
              Xor:  (at 71)
                Identifier: e (at 71)
                Identifier: f (at 71)
          IfStatement:  (at 72)
            Ulnot:  (at 72)
              Identifier: h (at 72)
            NonblockingSubstitution:  (at 73)
              Lvalue:  (at 73)
                Identifier: count (at 73)
              Rvalue:  (at 73)
                Ulnot:  (at 73)
                  Identifier: enable (at 73)
            NonblockingSubstitution:  (at 75)
              Lvalue:  (at 75)
                Identifier: count (at 75)
              Rvalue:  (at 75)
                Unot:  (at 75)
                  Identifier: g (at 75)
          NonblockingSubstitution:  (at 76)
            Lvalue:  (at 76)
              Identifier: count (at 76)
            Rvalue:  (at 76)
              Unot:  (at 76)
                And:  (at 76)
                  And:  (at 76)
                    Identifier: i (at 76)
                    Identifier: enable (at 76)
                  Ulnot:  (at 76)
                    Or:  (at 76)
                      Identifier: x (at 76)
                      Identifier: y (at 76)
