Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Ioport:  (at 3)
          Input: CLK, False (at 3)
        Ioport:  (at 4)
          Input: RST, False (at 4)
        Ioport:  (at 5)
          Input: enable, False (at 5)
        Ioport:  (at 6)
          Input: value, False (at 6)
            Width:  (at 6)
              IntConst: 31 (at 6)
              IntConst: 0 (at 6)
        Ioport:  (at 7)
          Output: led, False (at 7)
            Width:  (at 7)
              IntConst: 7 (at 7)
              IntConst: 0 (at 7)
      Decl:  (at 9)
        Reg: state, False (at 9)
          Width:  (at 9)
            IntConst: 7 (at 9)
            IntConst: 0 (at 9)
      Decl:  (at 10)
        Reg: cnt, False (at 10)
          Width:  (at 10)
            IntConst: 7 (at 10)
            IntConst: 0 (at 10)
      Decl:  (at 12)
        Reg: ncnt, False (at 12)
          Width:  (at 12)
            IntConst: 7 (at 12)
            IntConst: 0 (at 12)
      Decl:  (at 13)
        Reg: nstate, False (at 13)
          Width:  (at 13)
            IntConst: 7 (at 13)
            IntConst: 0 (at 13)
        Assign:  (at 13)
          Lvalue:  (at 13)
            Identifier: nstate (at 13)
          Rvalue:  (at 13)
            IntConst: 0 (at 13)
      Assign:  (at 14)
        Lvalue:  (at 14)
          Identifier: led (at 14)
        Rvalue:  (at 14)
          Partselect:  (at 14)
            Identifier: cnt (at 14)
            IntConst: 7 (at 14)
            IntConst: 0 (at 14)
      Assign:  (at 15)
        Lvalue:  (at 15)
          Identifier: state (at 15)
        Rvalue:  (at 15)
          IntConst: 0 (at 15)
      Always:  (at 16)
        SensList:  (at 16)
          Sens: posedge (at 16)
            Identifier: CLK (at 16)
          Sens: negedge (at 16)
            Identifier: RST (at 16)
        Block: None (at 17)
          IfStatement:  (at 18)
            Identifier: RST (at 18)
            NonblockingSubstitution:  (at 19)
              Lvalue:  (at 19)
                Identifier: cnt (at 19)
              Rvalue:  (at 19)
                Identifier: ncnt (at 19)
            NonblockingSubstitution:  (at 21)
              Lvalue:  (at 21)
                Identifier: cnt (at 21)
              Rvalue:  (at 21)
                Identifier: state (at 21)
      Always:  (at 23)
        SensList:  (at 23)
          Sens: all (at 23)
        Block: None (at 24)
          BlockingSubstitution:  (at 25)
            Lvalue:  (at 25)
              Identifier: cnt (at 25)
            Rvalue:  (at 25)
              Identifier: ncnt (at 25)
          BlockingSubstitution:  (at 26)
            Lvalue:  (at 26)
              Identifier: cnt (at 26)
            Rvalue:  (at 26)
              Identifier: nstate (at 26)
