Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Port: clk, None (at 2)
        Port: rst_n, None (at 2)
        Port: data, None (at 2)
        Port: add, None (at 2)
      Decl:  (at 3)
        Input: clk, False (at 3)
      Decl:  (at 4)
        Input: rst_n, False (at 4)
      Decl:  (at 5)
        Input: data, False (at 5)
          Width:  (at 5)
            IntConst: 3 (at 5)
            IntConst: 0 (at 5)
      Decl:  (at 6)
        Output: add, False (at 6)
          Width:  (at 6)
            IntConst: 2 (at 6)
            IntConst: 0 (at 6)
      Decl:  (at 7)
        Reg: add, False (at 7)
          Width:  (at 7)
            IntConst: 2 (at 7)
            IntConst: 0 (at 7)
      Always:  (at 8)
        SensList:  (at 8)
          Sens: posedge (at 8)
            Identifier: clk (at 8)
        Block: None (at 9)
          CaseStatement:  (at 10)
            Identifier: data (at 10)
            Case:  (at 11)
              IntConst: 0 (at 11)
              NonblockingSubstitution:  (at 11)
                Lvalue:  (at 11)
                  Identifier: add (at 11)
                Rvalue:  (at 11)
                  IntConst: 1 (at 11)
            Case:  (at 12)
              IntConst: 8 (at 12)
              IntConst: 9 (at 12)
              IntConst: 10 (at 12)
              IntConst: 11 (at 12)
              NonblockingSubstitution:  (at 12)
                Lvalue:  (at 12)
                  Identifier: add (at 12)
                Rvalue:  (at 12)
                  IntConst: 3 (at 12)
            Case:  (at 13)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
          CaseStatement:  (at 15)
            Identifier: data (at 15)
            Case:  (at 16)
              IntConst: 0 (at 16)
              NonblockingSubstitution:  (at 16)
                Lvalue:  (at 16)
                  Identifier: add (at 16)
                Rvalue:  (at 16)
                  IntConst: 1 (at 16)
            Case:  (at 17)
              IntConst: 8 (at 17)
              IntConst: 9 (at 17)
              IntConst: 10 (at 17)
              IntConst: 11 (at 17)
              NonblockingSubstitution:  (at 17)
                Lvalue:  (at 17)
                  Identifier: add (at 17)
                Rvalue:  (at 17)
                  IntConst: 3 (at 17)
      Always:  (at 20)
        SensList:  (at 0)
          Sens: all (at 0)
        Block: None (at 21)
          CaseStatement:  (at 22)
            Identifier: clk (at 22)
            Case:  (at 23)
              IntConst: 1 (at 23)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
            Case:  (at 24)
              IntConst: 2 (at 24)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
            Case:  (at 25)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
          CaseStatement:  (at 27)
            Identifier: df (at 27)
            Case:  (at 28)
              EventStatement:  (at 0)
                SensList:  (at 0)
                  Sens: all (at 0)
