Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Ioport:  (at 3)
          Input: CLK, False (at 3)
        Ioport:  (at 4)
          Input: RST, False (at 4)
        Ioport:  (at 5)
          Input: enable, False (at 5)
        Ioport:  (at 6)
          Input: value, False (at 6)
            Width:  (at 6)
              IntConst: 1 (at 6)
              IntConst: 0 (at 6)
        Ioport:  (at 7)
          Output: led, False (at 7)
            Width:  (at 7)
              IntConst: 7 (at 7)
              IntConst: 0 (at 7)
      Decl:  (at 9)
        Reg: count, False (at 9)
          Width:  (at 9)
            IntConst: 31 (at 9)
            IntConst: 0 (at 9)
      Decl:  (at 10)
        Reg: state, False (at 10)
          Width:  (at 10)
            IntConst: 7 (at 10)
            IntConst: 0 (at 10)
      Assign:  (at 11)
        Lvalue:  (at 11)
          Identifier: led (at 11)
        Rvalue:  (at 11)
          Partselect:  (at 11)
            Identifier: count (at 11)
            IntConst: 23 (at 11)
            IntConst: 16 (at 11)
      Always:  (at 13)
        SensList:  (at 13)
          Sens: posedge (at 13)
            Identifier: CLK (at 13)
          Sens: negedge (at 13)
            Identifier: RST (at 13)
        Block: None (at 14)
          CaseStatement:  (at 15)
            Identifier: value (at 15)
            Case:  (at 16)
              IntConst: 00 (at 16)
              NonblockingSubstitution:  (at 16)
                Lvalue:  (at 16)
                  Identifier: state (at 16)
                Rvalue:  (at 16)
                  Identifier: CLK (at 16)
            Case:  (at 17)
              IntConst: 01 (at 17)
              NonblockingSubstitution:  (at 17)
                Lvalue:  (at 17)
                  Identifier: state (at 17)
                Rvalue:  (at 17)
                  IntConst: 1 (at 17)
            Case:  (at 18)
              IntConst: 10 (at 18)
              NonblockingSubstitution:  (at 18)
                Lvalue:  (at 18)
                  Identifier: state (at 18)
                Rvalue:  (at 18)
                  IntConst: 0 (at 18)
            Case:  (at 19)
              IntConst: 11 (at 19)
              NonblockingSubstitution:  (at 19)
                Lvalue:  (at 19)
                  Identifier: state (at 19)
                Rvalue:  (at 19)
                  IntConst: 1 (at 19)
      Always:  (at 23)
        SensList:  (at 23)
          Sens: posedge (at 23)
            Identifier: CLK (at 23)
          Sens: negedge (at 23)
            Identifier: RST (at 23)
        Block: None (at 24)
          CaseStatement:  (at 25)
            Identifier: value (at 25)
            Case:  (at 26)
              IntConst: 2'b00 (at 26)
              NonblockingSubstitution:  (at 26)
                Lvalue:  (at 26)
                  Identifier: state (at 26)
                Rvalue:  (at 26)
                  Identifier: CLK (at 26)
            Case:  (at 27)
              IntConst: 2'b01 (at 27)
              NonblockingSubstitution:  (at 27)
                Lvalue:  (at 27)
                  Identifier: state (at 27)
                Rvalue:  (at 27)
                  IntConst: 1 (at 27)
            Case:  (at 28)
              IntConst: 2'b10 (at 28)
              NonblockingSubstitution:  (at 28)
                Lvalue:  (at 28)
                  Identifier: state (at 28)
                Rvalue:  (at 28)
                  IntConst: 0 (at 28)
            Case:  (at 29)
              IntConst: 2'b11 (at 29)
              NonblockingSubstitution:  (at 29)
                Lvalue:  (at 29)
                  Identifier: state (at 29)
                Rvalue:  (at 29)
                  IntConst: 0 (at 29)
