Source:  (at 1)
  Description:  (at 1)
    ModuleDef: top (at 1)
      Paramlist:  (at 0)
      Portlist:  (at 2)
        Ioport:  (at 3)
          Input: CLK, False (at 3)
        Ioport:  (at 4)
          Input: RST, False (at 4)
        Ioport:  (at 5)
          Input: enable, False (at 5)
        Ioport:  (at 6)
          Input: value, False (at 6)
            Width:  (at 6)
              IntConst: 1 (at 6)
              IntConst: 0 (at 6)
        Ioport:  (at 7)
          Output: led, False (at 7)
            Width:  (at 7)
              IntConst: 7 (at 7)
              IntConst: 0 (at 7)
      Decl:  (at 9)
        Reg: count, False (at 9)
          Width:  (at 9)
            IntConst: 31 (at 9)
            IntConst: 0 (at 9)
      Decl:  (at 10)
        Reg: state, False (at 10)
          Width:  (at 10)
            IntConst: 7 (at 10)
            IntConst: 0 (at 10)
      Assign:  (at 11)
        Lvalue:  (at 11)
          Identifier: led (at 11)
        Rvalue:  (at 11)
          Partselect:  (at 11)
            Identifier: count (at 11)
            IntConst: 23 (at 11)
            IntConst: 16 (at 11)
      Always:  (at 13)
        SensList:  (at 13)
          Sens: posedge (at 13)
            Identifier: CLK (at 13)
        Block: None (at 14)
          IfStatement:  (at 15)
            Eq:  (at 15)
              Identifier: value (at 15)
              IntConst: 2'b00 (at 15)
            NonblockingSubstitution:  (at 16)
              Lvalue:  (at 16)
                Identifier: count (at 16)
              Rvalue:  (at 16)
                Identifier: CLK (at 16)
            IfStatement:  (at 17)
              Eq:  (at 17)
                Identifier: value (at 17)
                IntConst: 2'b00 (at 17)
              NonblockingSubstitution:  (at 18)
                Lvalue:  (at 18)
                  Identifier: count (at 18)
                Rvalue:  (at 18)
                  IntConst: 1 (at 18)
              IfStatement:  (at 19)
                Eq:  (at 19)
                  Identifier: value (at 19)
                  IntConst: 2'b01 (at 19)
                NonblockingSubstitution:  (at 20)
                  Lvalue:  (at 20)
                    Identifier: count (at 20)
                  Rvalue:  (at 20)
                    IntConst: 0 (at 20)
      Always:  (at 23)
        SensList:  (at 23)
          Sens: posedge (at 23)
            Identifier: CLK (at 23)
          Sens: negedge (at 23)
            Identifier: RST (at 23)
        Block: None (at 24)
          IfStatement:  (at 25)
            Eq:  (at 25)
              Identifier: value (at 25)
              IntConst: 2'b00 (at 25)
            NonblockingSubstitution:  (at 26)
              Lvalue:  (at 26)
                Identifier: count (at 26)
              Rvalue:  (at 26)
                Identifier: CLK (at 26)
            IfStatement:  (at 27)
              Eq:  (at 27)
                Identifier: value (at 27)
                IntConst: 2'b01 (at 27)
              NonblockingSubstitution:  (at 28)
                Lvalue:  (at 28)
                  Identifier: state (at 28)
                Rvalue:  (at 28)
                  IntConst: 1 (at 28)
              IfStatement:  (at 29)
                Eq:  (at 29)
                  Identifier: value (at 29)
                  IntConst: 2'b01 (at 29)
                NonblockingSubstitution:  (at 30)
                  Lvalue:  (at 30)
                    Identifier: count (at 30)
                  Rvalue:  (at 30)
                    IntConst: 1 (at 30)
                NonblockingSubstitution:  (at 31)
                  Lvalue:  (at 31)
                    Identifier: count (at 31)
                  Rvalue:  (at 31)
                    IntConst: 0 (at 31)
      Always:  (at 34)
        SensList:  (at 34)
          Sens: posedge (at 34)
            Identifier: CLK (at 34)
          Sens: negedge (at 34)
            Identifier: RST (at 34)
        Block: None (at 35)
          IfStatement:  (at 36)
            Eq:  (at 36)
              Identifier: value (at 36)
              IntConst: 2'b00 (at 36)
            NonblockingSubstitution:  (at 37)
              Lvalue:  (at 37)
                Identifier: count (at 37)
              Rvalue:  (at 37)
                Identifier: CLK (at 37)
            IfStatement:  (at 38)
              Eq:  (at 38)
                Identifier: value (at 38)
                IntConst: 2'b01 (at 38)
              NonblockingSubstitution:  (at 39)
                Lvalue:  (at 39)
                  Identifier: state (at 39)
                Rvalue:  (at 39)
                  IntConst: 1 (at 39)
              IfStatement:  (at 40)
                Eq:  (at 40)
                  Identifier: value (at 40)
                  IntConst: 2'b00 (at 40)
                NonblockingSubstitution:  (at 41)
                  Lvalue:  (at 41)
                    Identifier: count (at 41)
                  Rvalue:  (at 41)
                    IntConst: 1 (at 41)
                NonblockingSubstitution:  (at 42)
                  Lvalue:  (at 42)
                    Identifier: count (at 42)
                  Rvalue:  (at 42)
                    IntConst: 0 (at 42)
      Always:  (at 45)
        SensList:  (at 45)
          Sens: posedge (at 45)
            Identifier: CLK (at 45)
          Sens: negedge (at 45)
            Identifier: RST (at 45)
        Block: None (at 46)
          CaseStatement:  (at 47)
            Identifier: value (at 47)
            Case:  (at 48)
              IntConst: 2'b00 (at 48)
              NonblockingSubstitution:  (at 48)
                Lvalue:  (at 48)
                  Identifier: state (at 48)
                Rvalue:  (at 48)
                  Identifier: CLK (at 48)
            Case:  (at 49)
              IntConst: 2'b01 (at 49)
              NonblockingSubstitution:  (at 49)
                Lvalue:  (at 49)
                  Identifier: state (at 49)
                Rvalue:  (at 49)
                  IntConst: 1 (at 49)
            Case:  (at 50)
              IntConst: 2'b00 (at 50)
              NonblockingSubstitution:  (at 50)
                Lvalue:  (at 50)
                  Identifier: state (at 50)
                Rvalue:  (at 50)
                  IntConst: 0 (at 50)
      Always:  (at 54)
        SensList:  (at 54)
          Sens: posedge (at 54)
            Identifier: CLK (at 54)
          Sens: negedge (at 54)
            Identifier: RST (at 54)
        Block: None (at 55)
          CaseStatement:  (at 56)
            Identifier: value (at 56)
            Case:  (at 57)
              IntConst: 2'b01 (at 57)
              NonblockingSubstitution:  (at 57)
                Lvalue:  (at 57)
                  Identifier: state (at 57)
                Rvalue:  (at 57)
                  Identifier: CLK (at 57)
            Case:  (at 58)
              IntConst: 2'b01 (at 58)
              NonblockingSubstitution:  (at 58)
                Lvalue:  (at 58)
                  Identifier: state (at 58)
                Rvalue:  (at 58)
                  IntConst: 1 (at 58)
            Case:  (at 59)
              IntConst: 2'b00 (at 59)
              NonblockingSubstitution:  (at 59)
                Lvalue:  (at 59)
                  Identifier: state (at 59)
                Rvalue:  (at 59)
                  IntConst: 0 (at 59)
      Always:  (at 63)
        SensList:  (at 63)
          Sens: posedge (at 63)
            Identifier: CLK (at 63)
          Sens: negedge (at 63)
            Identifier: RST (at 63)
        Block: None (at 64)
          CaseStatement:  (at 65)
            Identifier: value (at 65)
            Case:  (at 66)
              IntConst: 2'b00 (at 66)
              NonblockingSubstitution:  (at 66)
                Lvalue:  (at 66)
                  Identifier: state (at 66)
                Rvalue:  (at 66)
                  Identifier: CLK (at 66)
            Case:  (at 67)
              IntConst: 2'b01 (at 67)
              NonblockingSubstitution:  (at 67)
                Lvalue:  (at 67)
                  Identifier: state (at 67)
                Rvalue:  (at 67)
                  IntConst: 1 (at 67)
            Case:  (at 68)
              IntConst: 2'b01 (at 68)
              NonblockingSubstitution:  (at 68)
                Lvalue:  (at 68)
                  Identifier: state (at 68)
                Rvalue:  (at 68)
                  IntConst: 0 (at 68)
